import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "@/components/Providers/LayoutWrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className="antialiased flex">
        <LayoutWrapper>{children}</LayoutWrapper>
        </body>
        </html>
    );
}
